src/objects/SalesDistrict__c.object
<CustomObject>
    <fields>
        <fullName>CountryIsoCode__c</fullName>
        <label>Country ISO Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesDistrictKey__c</fullName>
        <label>Sales District Key</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SalesDistricts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ServiceSalesDistricts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales District</label>
    <nameField>
        <label>Sales District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Cache_SalesDistrict.cls
/**
 * @description Sample implementation of the CacheBuilder interface for a SalesDistrict__c by District Key cache.
 * @author  Daniel Stange
 * @date 2019-08-02
 *
 */

public without sharing class Cache_SalesDistrict implements Cache.CacheBuilder {

    /**
     * @description mandatory internal method to gracefully retrieve data and handle potential cache misses
     * @param districtKey
     * @return cached items as an Object
     */
    public Object doLoad(String districtKey) {
        SalesDistrict__c oSalesDistrict = (SalesDistrict__c) [
                SELECT Id,
                        Name,
                        Country__c,
                        CountryIsoCode__c,
                        SalesDistrictKey__c,
                        SalesManager__c,
                        ServiceManager__c,
                        isDefault__c
                FROM SalesDistrict__c
                WHERE SalesDistrictKey__c = :districtKey
        ];
        return oSalesDistrict;
    }
}