force-app/main/default/objects/Account/fields/SalesDistrict__c.field-meta.xml
<CustomField>
    <fullName>SalesDistrict__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales district assigned to the account</description>
    <label>Sales District</label>
    <referenceTo>SalesDistrict__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/SalesDistrict__c.object
<CustomObject>
    <fields>
        <fullName>SalesManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SalesDistricts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales District</label>
    <nameField>
        <label>Sales District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Account_Trg.cls
/**
 * Trigger handler for Account_Trg trigger
 * - fills SalesDistruct__c lookup field and assigns record to the Sales Manager
 */
public class Account_Trg extends TriggerHandler {
	

	public override void beforeInsert() {

		this.fillSalesDistrict();
	}

	public override void beforeUpdate() {

		this.fillSalesDistrict();
	}

	public override void afterUndelete() {

		this.fillSalesDistrict();
	}

	/**
	 * Retrieve a matching sales district from the cache to fill SalesDistrict__C relation 
	 * or use the default
	 */
	private void fillSalesDistrict() {

		for (Account a : (List<Account>) Trigger.new) {

			String salesDistrictKey = a.BillingCountryCode + a.BillingPostalCode.left(2);

			SalesDistrict__c sd = SampleCacheManager.getDistrict(salesDistrictKey);

			if (sd != NULL) {

				a.OwnerId = sd.SalesManager__c;
				a.SalesDistrict__c = sd.Id;	
			}
		}
	}
}