force-app/main/default/objects/Account/fields/SalesDistrict__c.field-meta.xml
<CustomField>
    <fullName>SalesDistrict__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales district assigned to the account</description>
    <label>Sales District</label>
    <referenceTo>SalesDistrict__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CacheSetting__mdt/CacheSetting__mdt.object-meta.xml
<CustomObject>
    <description>Settings for the Platform Cache Demo</description>
    <label>CacheSetting</label>
    <pluralLabel>CacheSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CacheSetting__mdt/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <label>Handler</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CustomApex</fullName>
                <default>true</default>
                <label>CustomApex</label>
            </value>
            <value>
                <fullName>CacheBuilder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/SalesDistrict__c.object
<CustomObject>
    <fields>
        <fullName>SalesManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SalesDistricts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales District</label>
    <nameField>
        <label>Sales District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TrgHandler_Account.cls
/**
 * @author	Daniel Stange
 * @date    2019-06-17
 * @description Trigger handler for TrgHandler_Account trigger
 * 	- fills SalesDistruct__c lookup field and assigns record to the Sales Manager
 */
public class TrgHandler_Account extends TriggerHandler {
    
    private String cacheHandler;
    
    public TrgHandler_Account() {
    
        CacheSetting__mdt cacheSetting = [SELECT Handler__c FROM CacheSetting__mdt WHERE DeveloperName = 'CacheDemo'];
        this.cacheHandler = (cacheSetting != null) ? cacheSetting.Handler__c : 'CacheBuilder';
    }
        
	
	public override void beforeInsert() {
		this.fillSalesDistrict();
	}

	public override void beforeUpdate() {
		this.fillSalesDistrict();
	}


	/**
	 * @description Retrieve a matching sales district from the cache to fill SalesDistrict__C relation
	 * or use the default
	 */
	private void fillSalesDistrict() {

		for (Account a : (List<Account>) Trigger.new) {

			String salesDistrictKey = a.BillingCountryCode + a.BillingPostalCode.left(2);
			SalesDistrict__c sd;
            
            if (this.cacheHandler == 'CustomApex') {
            	sd = Cache_SalesDistrictCustom.getDistrict(salesDistrictKey);
            }
            else {
                sd = (SalesDistrict__c) Cache.Org.get(Cache_SalesDistrict.class, salesDistrictKey);
            }
            
			if (sd != null) {

				a.OwnerId = sd.SalesManager__c;
				a.SalesDistrict__c = sd.Id;	
			}
		}
	}
}